vich_uploader:
    db_driver: orm
    mappings:
        enchere_image:
            uri_prefix: /uploads/enchere
            upload_destination: '%kernel.project_dir%/public/uploads/enchere'
            namer: 'Vich\UploaderBundle\Naming\SmartUniqueNamer'
            delete_on_remove: true
            delete_on_update: false
